"""ideation sessions

Revision ID: 99285c349815
Revises: b71477bc4b38
Create Date: 2026-07-02 22:45:43.156799
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '99285c349815'
down_revision: Union[str, None] = 'b71477bc4b38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ideation_sessions',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('complete', 'failed', name='ideation_status', native_enum=False), nullable=False),
    sa.Column('hypotheses', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('meta_review', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ideation_sessions_org_id'), 'ideation_sessions', ['org_id'], unique=False)
    op.create_index(op.f('ix_ideation_sessions_project_id'), 'ideation_sessions', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ideation_sessions_project_id'), table_name='ideation_sessions')
    op.drop_index(op.f('ix_ideation_sessions_org_id'), table_name='ideation_sessions')
    op.drop_table('ideation_sessions')
    # ### end Alembic commands ###
